version: '3.3'

services:

  app:
    container_name: application
    build: ./app
    image: golang_app:latest
    
  redis:
    container_name: redis
    build: ./redis
    image: redis_local:latest
    ports:
      - 6379:6379
      - 6380:6380

  web:
    container_name: nginx
    build: ./nginx
    ports:
      - 8081:8089
    volumes:
      - ./nginx/application.conf:/etc/nginx/conf.d/app.conf
