version: '3.3'

services:

  app:
    container_name: application
    build: ./app
    image: golang_app:latest
    
  redis:
    container_name: redis
    build: ./redis
    image: redis_local:latest
    environment:
            REDIS_PASSWORD: 
            REDIS_TLS_ENABLED: "yes"
            REDIS_TLS_CERT_FILE: /usr/local/etc/redis/redis.crt
            REDIS_TLS_KEY_FILE: /usr/local/etc/redis/redis.key
            REDIS_TLS_CA_FILE: /usr/local/etc/redis/ca.crt
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./tls/redis.crt:/usr/local/etc/redis/tls/redis.crt
      - ./tls/redis.key:/usr/local/etc/redis/tls/redis.key
      - ./tls/ca.crt:/usr/local/etc/redis/tls/ca.crt

  web:
    container_name: nginx
    build: ./nginx
    ports:
      - 8081:8089
    volumes:
      - ./nginx/application.conf:/etc/nginx/conf.d/app.conf
    
